# Generated by Django 2.2.6 on 2019-10-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='static/img/avatar.svg', upload_to=''),
        ),
    ]
