# Generated by Django 2.2.6 on 2019-10-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='static/img/avatar.svg', upload_to='images/'),
        ),
    ]
