# Generated by Django 2.2.6 on 2019-10-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_auto_20191028_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='static/img/user_avatar/avatar.svg', upload_to='static/img/user_avatar'),
        ),
    ]
