# Generated by Django 2.2.6 on 2019-10-28 18:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_auto_20191028_1751'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='answer',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default='Answer on question'),
        ),
    ]
